### ISSUE TITLE
Links and label issue on mobile

### ISSUE THREAD

**Issue by matthewpeixoto** [matthewpeixoto/dog-rescue-pattern-library#7]
The hero-banner's span button needs to be pressed twice on mobile to work. The first tap only triggers it's hover state. Pressing on the hero-banner's image works as expected.

Same issue is found with the "Continue" labels at the bottom of each application section.

**Hero-banner issue:** https://github.com/matthewpeixoto/dog-rescue-pattern-library/blob/gh-pages/pages/home.html#L62-L75

**Application issue:** https://github.com/matthewpeixoto/dog-rescue-pattern-library/blob/gh-pages/pages/application.html#L252-L259

@thomasjbradley

**Comment by thomasjbradley** [comment]
It's because you're using `::after` to create the underline. The mobile browser interprets that as something that really needs to be shown on mobile because it seems to be a critical content piece.

My suggested solution would be to just disable the hover on small screens. Unfortunately it isn't a perfect solution because big tablets would still have a problem.

**Comment by matthewpeixoto** [comment]
Thank you @thomasjbradley. I was using <code>::after</code> to add a white overlay to my buttons when hovered so I was able to simply change the colours instead to fix the issue.
